### ISSUE TITLE
Request: integration with the react chart library

### ISSUE THREAD

**Issue by lkarvec** [julianna-langston/chartjs-plugin-a11y-legend#25]
I like this library but it seems to just not function with the react-chartjs-2 library.  I've tried a couple different methods of importing it in and it doesn't want to plug and play.

So far I've used:
chartJS.register( ) to set it - Unsuccessful and doesn't allow the graph to render
The plugin property on the Bar component  - error dump, below
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'reviveFocusBox')

Call Stack
Object.beforeDraw
node_modules\chartjs-plugin-a11y-legend\dist\plugin.mjs (118:0)
callback
node_modules\chart.js\dist\chunks\helpers.segment.js (79:0)
PluginService._notify
node_modules\chart.js\dist\chart.js (5067:24)
PluginService.notify
node_modules\chart.js\dist\chart.js (5050:0)
Chart.notifyPlugins
node_modules\chart.js\dist\chart.js (6328:0)
Chart.draw
node_modules\chart.js\dist\chart.js (6031:0)
Chart.render
node_modules\chart.js\dist\chart.js (6014:0)
Chart.update
node_modules\chart.js\dist\chart.js (5899:0)
Chart.eval
node_modules\chart.js\dist\chart.js (5631:33)
Chart.eval [as _doResize]
node_modules\chart.js\dist\chunks\helpers.segment.js (597:0)
Chart._resize
node_modules\chart.js\dist\chart.js (5720:0)
Chart.resize
node_modules\chart.js\dist\chart.js (5691:0)
attached
node_modules\chart.js\dist\chart.js (6262:0)
Chart.bindResponsiveEvents
node_modules\chart.js\dist\chart.js (6274:0)
Chart.bindEvents
node_modules\chart.js\dist\chart.js (6218:0)
Chart._initialize
node_modules\chart.js\dist\chart.js (5677:0)
new Chart
node_modules\chart.js\dist\chart.js (5640:0)
renderChart
node_modules\react-chartjs-2\dist\index.js (85:0)
eval
node_modules\react-chartjs-2\dist\index.js (149:0)
commitHookEffectListMount
node_modules\react-dom\cjs\react-dom.development.js (23150:0)
commitPassiveMountOnFiber
node_modules\react-dom\cjs\react-dom.development.js (24926:0)
commitPassiveMountEffects_complete
node_modules\react-dom\cjs\react-dom.development.js (24891:0)
commitPassiveMountEffects_begin
node_modules\react-dom\cjs\react-dom.development.js (24878:0)
commitPassiveMountEffects
node_modules\react-dom\cjs\react-dom.development.js (24866:0)
flushPassiveEffectsImpl
node_modules\react-dom\cjs\react-dom.development.js (27039:0)
flushPassiveEffects
node_modules\react-dom\cjs\react-dom.development.js (26984:0)
commitRootImpl
node_modules\react-dom\cjs\react-dom.development.js (26935:0)
commitRoot
node_modules\react-dom\cjs\react-dom.development.js (26682:0)
performSyncWorkOnRoot
node_modules\react-dom\cjs\react-dom.development.js (26117:0)
flushSyncCallbacks
node_modules\react-dom\cjs\react-dom.development.js (12042:0)
flushSync
node_modules\react-dom\cjs\react-dom.development.js (26201:0)
scheduleRefresh
node_modules\react-dom\cjs\react-dom.development.js (27795:0)
renderer.scheduleRefresh
chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend_compact.js (5135:16)
eval
node_modules\next\dist\compiled\react-refresh\cjs\react-refresh-runtime.development.js (265:0)
Set.forEach
<anonymous>
Object.performReactRefresh
node_modules\next\dist\compiled\react-refresh\cjs\react-refresh-runtime.development.js (254:0)
eval
node_modules\next\dist\compiled\@next\react-refresh-utils\dist\internal\helpers.js (124:0)
```

**Comment by julianna-langston** [comment]
It wasn't built to work in React, but I'll look into extending it to work within the React framework.

**Comment by lkarvec** [comment]
It would be super cool, and I'd love to contribute since I'm using this for work with NIH right now.

**Comment by julianna-ciq** [comment]
I've just published v0.1.0, which should play nicely with react-chartjs-2.

@lkarvec Can you try out the new version and see if it meets your needs?

**Comment by lkarvec** [comment]
Yeah Ill let you know come Tuesday since monday is a holiday. Thanks so much, we actually were planning for this to be done like 2 months from now on your side lolSent from my iPhoneOn May 27, 2023, at 12:57 PM, julianna-ciq ***@***.***> wrote:﻿
I've just published v0.1.0, which should play nicely with react-chartjs-2.
@lkarvec Can you try out the new version and see if it meets your needs?

**Comment by lkarvec** [comment]
Okay so I get an issue now @julianna-ciq @julianna-langston 
![image](https://github.com/julianna-langston/chartjs-plugin-a11y-legend/assets/47825690/89b86c5c-7e27-430f-aaff-9094af07f582)
Legend is highlighted there, and the indication for where it is tabbed/focused is off the graph in the red section here.  It does this for both graphs here, just shoves it all the way to the right.  Want me to open this up as a different issue or is there a fix to this?

**Comment by julianna-langston** [comment]
@lkarvec  Do you mind opening a new issue, and include a CodeSandbox or code examples that can reproduce the problem? Be advised that this is potentially a CSS issue, so things like the chart's **parent** could impact the behavior.
