### ISSUE TITLE
Position relative breaks positioning

### ISSUE THREAD

**Issue by brian-patrick-3** [julianna-langston/chartjs-plugin-a11y-legend#60]
When using `position: relative;` on the parent container of the canvas as [outlined in the Chart.js docs here](https://www.chartjs.org/docs/latest/configuration/responsive.html#important-note), the positioning of the legend focus indicator is incorrect.

**Comment by julianna-ciq** [comment]
This fix will be released in v0.1.1, which will go out around Monday
